### 创建张量的基本创建方式
1. torch.tensor 根据指定数量创建张量
2. torch.Tensor 根据形状创建张量，其也可以创建指定数量的张量
3. torch.IntTensor、torch.FloatTTensor、torch.DoubleTensor 创建指定类型的张量

张量的默认类型是：Float32

In [5]:
import torch
import numpy as np

def create_tensor_1():
    t1 = torch.tensor(10)
    print(t1, "type:" + str(type(t1)))
    print("-" * 40)

    data = [[1,2,3],[4,5,6],[7,8,9]]
    t2 = torch.tensor(data)
    print(t2, "type:" + str(type(t2)))
    print("-" * 40)

    data = np.random.randint(0, 10, size=(2, 3))
    t3 = torch.tensor(data)
    print(t3, "type:" + str(type(t3)))
    print("-" * 40)

def create_tensor_2():
    t1 = torch.Tensor(10)
    print(t1, "type:" + str(type(t1)))
    print("-" * 40)

    data = [[1,2,3],[4,5,6],[7,8,9]]
    t2 = torch.Tensor(data)
    print(t2, "type:" + str(type(t2)))
    print("-" * 40)

    data = np.random.randint(0, 10, size=(2, 3))
    t3 = torch.Tensor(data)
    print(t3, "type:" + str(type(t3)))
    print("-" * 40)

    t4 = torch.Tensor(2, 3)
    print(t4, "type:" + str(type(t4)))
    print("-" * 40)

def create_tensor_3():
    t1 = torch.IntTensor(10)
    print(t1, "type:" + str(type(t1)))
    print("-" * 40)

    data = [[1,2,3],[4,5,6],[7,8,9]]
    t2 = torch.IntTensor(data)
    print(t2, "type:" + str(type(t2)))
    print("-" * 40)

    data = np.random.randint(0, 10, size=(2, 3))
    t3 = torch.IntTensor(data)
    print(t3, "type:" + str(type(t3)))
    print("-" * 40)

    t4 = torch.IntTensor(2, 3)
    print(t4, "type:" + str(type(t4)))
    print("-" * 40)

if __name__ == '__main__':
    # create_tensor_1()
    # create_tensor_2()
    create_tensor_3()

tensor([-1006369552,        1439,           0,           0,           0,
                  0,           0,           0,           0,           0],
       dtype=torch.int32) type:<class 'torch.Tensor'>
----------------------------------------
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32) type:<class 'torch.Tensor'>
----------------------------------------
tensor([[9, 3, 7],
        [0, 7, 6]], dtype=torch.int32) type:<class 'torch.Tensor'>
----------------------------------------
tensor([[-1006435488,        1439,           0],
        [          0,           0,           0]], dtype=torch.int32) type:<class 'torch.Tensor'>
----------------------------------------


### 创建0,1,指定值张量
1. torch.ones  torch.ones_like  创建全1张量
2. torch.zeros torch.zeros_like 创建全0张量
3. torch.full  torch.full_like  创建全为指定值张量

In [10]:
t1 = torch.zeros((2,3))
print(t1, "type:" + str(type(t1)))
print("-" * 40)
data = [[1,2,3],[4,5,6],[7,8,9]]
t2 = torch.tensor(data)
print(t2, "type:" + str(type(t2)))
t3 = torch.zeros_like(t2)
print(t3, "type:" + str(type(t3)))
print("*" * 40)

t1 = torch.ones((2,3))
print(t1, "type:" + str(type(t1)))
print("-" * 40)
data = [[1,2,3],[4,5,6],[7,8,9]]
t2 = torch.tensor(data)
print(t2, "type:" + str(type(t2)))
t3 = torch.ones_like(t2)
print(t3, "type:" + str(type(t3)))
print("*" * 40)

t1 = torch.full(size=(2,3), fill_value=255)
print(t1, "type:" + str(type(t1)))
print("-" * 40)
data = [[1,2,3],[4,5,6],[7,8,9]]
t2 = torch.tensor(data)
print(t2, "type:" + str(type(t2)))
t3 = torch.full_like(input=t2, fill_value=255)
print(t3, "type:" + str(type(t3)))
print("*" * 40)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) type:<class 'torch.Tensor'>
----------------------------------------
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) type:<class 'torch.Tensor'>
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) type:<class 'torch.Tensor'>
****************************************
tensor([[1., 1., 1.],
        [1., 1., 1.]]) type:<class 'torch.Tensor'>
----------------------------------------
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) type:<class 'torch.Tensor'>
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]) type:<class 'torch.Tensor'>
****************************************
tensor([[255, 255, 255],
        [255, 255, 255]]) type:<class 'torch.Tensor'>
----------------------------------------
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) type:<class 'torch.Tensor'>
tensor([[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]) type:<class 'torch.Tensor'>
************************************

### 创建线性与随机张量
1. torch.arange() torch.linspace() 创建线性张量
2. torch.random.initial_seed() torch.random.manual_seed() 随机种子设置
3. torch.rand/randn() 创建随机浮点类型张量
4. torch.randint(low, high, size=()) 创建随机整数类型张量

In [16]:
# 创建线性张量
# arange 指定范围的张量
# 参数：开始，结束，步长
t1 = torch.arange(0, 10, 2)
print(t1, "type:" + str(type(t1)))
print("-" * 40)
# linspace  等差数列
# 参数：开始，结束，元素个数
t2 = torch.linspace(1, 10, 4)
print(t2, "type:" + str(type(t2)))
print("*" * 40)


# 设置随机数种子
torch.initial_seed()  # 默认根据当前系统的时间戳作为随机数种子
torch.manual_seed(42) # 设置指定的随机数种子

# 创建随机张量
# rand是均匀分布（0,1）随机张量
t1 = torch.rand(size=(2, 3))
print(t1, "type:" + str(type(t1)))
print("-" * 40)
# randn是正态分布的随机张量
t2 = torch.randn(size=(2, 3))
print(t2, "type:" + str(type(t2)))
print("*" * 40)

# 创建随机证书张量
t1 = torch.randint(1, 10, size=(3,5))
print(t1, "type:" + str(type(t1)))
print("*" * 40)

tensor([0, 2, 4, 6, 8]) type:<class 'torch.Tensor'>
----------------------------------------
tensor([ 1.,  4.,  7., 10.]) type:<class 'torch.Tensor'>
****************************************
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) type:<class 'torch.Tensor'>
----------------------------------------
tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]]) type:<class 'torch.Tensor'>
****************************************
tensor([[4, 5, 5, 9, 2],
        [6, 9, 5, 3, 1],
        [2, 2, 4, 4, 8]]) type:<class 'torch.Tensor'>
****************************************
