### 张量的基本运算
加减乘除取负号：
add、sub、mul、div、neg
add_、sub_、mul_、div_、neg_、（其中带下划线的版本会修改原数据） -> inplace = True

In [3]:
import torch

t1 = torch.tensor([1,2,3])
t2 = t1.add(10)
t3 = t1 + 10
t4 = t1.add_(10) # 修改原数据
print(f"t1: {t1}")
print(f"t2: {t2}")
print(f"t3: {t3}")
print(f"t3: {t4}")

## 之后运算同理

t1: tensor([11, 12, 13])
t2: tensor([11, 12, 13])
t3: tensor([11, 12, 13])
t3: tensor([11, 12, 13])


### 点乘运算与矩阵运算
点乘是相同形状的张量对应位置的元素相乘，使用 mul 或 * 实现
矩阵相乘要求第一个矩阵 shape(n,m)，第二个矩阵 shape(m, p) -> shape(n, p)，使用 @ 或 torch.matmul 进行矩阵相乘

In [6]:
import torch

# 点乘运算
t1 = torch.tensor([[1,2,3], [4, 5, 6]])
t2 = torch.tensor([[1,2,3], [4, 5, 6]])

t3 = t1 * t2
t3 = torch.mul(t1, t2)
print(t3)

# 矩阵乘法
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[1, 2], [4, 5], [3, 6]])

t3 = t1 @ t2
t3 = torch.matmul(t1, t2)
print(t3)

tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[18, 30],
        [42, 69]])


### 张量运算函数
均值  mean()
平方根 sqrt()
求和  sum()
指数计算 pow(x, n) exp() -> e^n  n是矩阵中的每个元素
对数计算 log() log2() log10()
其中 sum(),min(),max(),mean()  -> 都有dim参数，0表示列，1表示行

In [18]:
import torch

t1 = torch.tensor([
    [1,2,3],
    [2,3,4]
], dtype=torch.float)
print(t1.sum(dim=0))
print(t1.sum(dim=1))
print(t1.sum())
print("-" * 40)

print(t1.max(dim=0))
print(t1.max(dim=1))
print(t1.max())
print("-" * 40)

print(t1.mean(dim=0))
print(t1.mean(dim=1))
print(t1.mean())
print("-" * 40)

print(t1.pow(2))
print(t1 ** 2)
print(t1.sqrt())
print(t1.exp())
print(t1.log())
print(t1.log2())
print(t1.log10())

tensor([3., 5., 7.])
tensor([6., 9.])
tensor(15.)
----------------------------------------
torch.return_types.max(
values=tensor([2., 3., 4.]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([2, 2]))
tensor(4.)
----------------------------------------
tensor([1.5000, 2.5000, 3.5000])
tensor([2., 3.])
tensor(2.5000)
----------------------------------------
tensor([[ 1.,  4.,  9.],
        [ 4.,  9., 16.]])
tensor([[ 1.,  4.,  9.],
        [ 4.,  9., 16.]])
tensor([[1.0000, 1.4142, 1.7321],
        [1.4142, 1.7321, 2.0000]])
tensor([[ 2.7183,  7.3891, 20.0855],
        [ 7.3891, 20.0855, 54.5981]])
tensor([[0.0000, 0.6931, 1.0986],
        [0.6931, 1.0986, 1.3863]])
tensor([[0.0000, 1.0000, 1.5850],
        [1.0000, 1.5850, 2.0000]])
tensor([[0.0000, 0.3010, 0.4771],
        [0.3010, 0.4771, 0.6021]])


### 张量的索引操作
1. 简单行列索引
2. 列表索引
3. 范围索引
4. 布尔索引
5. 多维索引

In [44]:
import torch

torch.manual_seed(42)

t = torch.randint(1, 10, (5,5))
print(f"t: {t}")
print("-" * 40)
# 简单行列
print(t[1])
print(t[1, :])
print(t[:, 2])
print("-" * 40)
# 列表索引，前边的表示行，后边的表示列
# 返回(0,1) (1,2)两个位置的元素
print(t[[0,1], [1,2]])
# 返回(1,2) (3,4)两个位置的元素
print(t[[1, 3], [2, 4]])
# 获取第0，1行的 1，2列 共四个元素
print(t[[[0], [1]], [1,2]])
print("-" * 40)

# 范围索引
print(t[:3, :2])
print(t[1:, :2])
# 所有奇数行、偶数列，后边是步长
print(t[1::2, 0::2])
print("-" * 40)

# 布尔索引
print(t[torch.tensor([True, False, False, True, True]), :])
# 第三列，大于5的行数据
print(t[t[:, 2] > 5])

# 第二行，大于5的列数据
# 理解1：在第二行的基础上，找到该行大于5的列索引，然后找到所有行中对应列的元素
print(t[:, t[1, :] > 5])
print(t[:, t[1]>5])

# 理解2： 在第二行的基础上，找到行所有列中大于5的元素
print(t[1, t[1, :] > 5])
print("-" * 40)

# 多维索引
t1 = torch.randint(1, 10, (2, 3, 4))
print(f"t1: {t1}")

# 获取0轴上的第一个数据
print(t1[0, :, :])
# 获取1轴上的第一个数据
print(t1[:, 0, :])
#获取2轴上的第一个数据
print(t1[:, :, 0])

t: tensor([[7, 6, 8, 5, 1],
        [3, 8, 6, 5, 3],
        [5, 5, 9, 1, 1],
        [5, 3, 5, 4, 5],
        [5, 9, 2, 6, 9]])
----------------------------------------
tensor([3, 8, 6, 5, 3])
tensor([3, 8, 6, 5, 3])
tensor([8, 6, 9, 5, 2])
----------------------------------------
tensor([6, 6])
tensor([6, 5])
tensor([[6, 8],
        [8, 6]])
----------------------------------------
tensor([[7, 6],
        [3, 8],
        [5, 5]])
tensor([[3, 8],
        [5, 5],
        [5, 3],
        [5, 9]])
tensor([[3, 6, 3],
        [5, 5, 5]])
----------------------------------------
tensor([[7, 6, 8, 5, 1],
        [5, 3, 5, 4, 5],
        [5, 9, 2, 6, 9]])
tensor([[7, 6, 8, 5, 1],
        [3, 8, 6, 5, 3],
        [5, 5, 9, 1, 1]])
tensor([[6, 8],
        [8, 6],
        [5, 9],
        [3, 5],
        [9, 2]])
tensor([[6, 8],
        [8, 6],
        [5, 9],
        [3, 5],
        [9, 2]])
tensor([8, 6])
----------------------------------------
t1: tensor([[[5, 3, 1, 2],
         [2, 4, 4, 8],

### 张量的形状操作
1. reshape()   在保证张量数据不变的前提下改变数据维度，将其转换为指定的形状
2. squeeze()   删除形状为1的维度(降维)
3. unsqueeze() 添加形状为1的维度(升维)
4. transpose() 交换张量形状的指定维度，例如：一个张量的形状为(2, 3, 4)，可以通过transpose把3，4进行交换，将张量的形状变为(2, 4, 3).
5. permute()   在transpose的基础上，可以一次交换更多的维度
6. view()      可以用于修改张量的形状，只能用于修改连续的张量。在Pytorch中，有些张量的底层数据在内存中的存储顺序与其在张量中的逻辑顺序不一致，view函数无法对这样的张量进行变形处理，例如：一个张量经过了transpose或permute处理之后，就无法使用view函数进行形状操作
7. contiguous()把不连续的张量转为连续的张量，即：基于张量中显示的顺序，修改内存中的存储顺序
8. is_contiguous() 判断张量是否是连续的

In [65]:
import torch

torch.manual_seed(42)
t1 = torch.randint(1, 10, size=(2,3))
print(f"t1: {t1}, shape: {t1.shape}, row: {t1.shape[0]}, column: {t1.shape[1]}")

# 通过reshape把t1 -> 3r2c, 1r6c, 6r1c
t2 = t1.reshape(3, 2)
t2 = t1.reshape(1, 6)
t2 = t1.reshape(6, 1)
print(f"t1: {t2}, shape: {t2.shape}, row: {t2.shape[0]}, column: {t2.shape[1]}")

t1 = torch.randint(1, 10, size=(2,3))
print(f"t1: {t1}, shape: {t1.shape}, rows: {t1.shape[0]}, columns: {t1.shape[1]}")
# 在0维添加一个维度
t2 = t1.unsqueeze(0)
print(f"t2: {t2}, shape: {t2.shape}")
# 在1维添加一个维度
t3 = t1.unsqueeze(1)
print(f"t2: {t3}, shape: {t3.shape}")

t1 = torch.randint(1, 10, size=(2, 1, 3, 1, 1))
print(f"t1: {t1}, shape: {t1.shape}")
# 删除所有维度为1的维度
t2 = t1.squeeze()
print(f"t2: {t2}, shape: {t2.shape}")

t1 = torch.randint(1, 10, size=(2, 3, 4))
print(f"t1: {t1}, shape: {t1.shape}")
t2 = t1.transpose(0, 1)
print(f"t2: {t2}, shape: {t2.shape}")
t3 = t1.permute(2, 0, 1)
print(f"t3: {t3}, shape: {t3.shape}")

t1 = torch.randint(1, 10, size=(2, 3 ,4))
print(t1.is_contiguous())
t2 = t1.view(3, 2, 4)
print(f"t2: {t2}, shape: {t2.shape}")

t3 = t1.transpose(0, 1)
print(f"t3: {t3}, shape: {t3.shape}")
print(t3.is_contiguous())
# t2 = t3.view(4, 2, 3)
t2 = t3.contiguous().view(4, 2, 3)
print(f"t2: {t2}, shape: {t2.shape}")
print(t2.is_contiguous())

t1: tensor([[7, 6, 8],
        [5, 1, 3]]), shape: torch.Size([2, 3]), row: 2, column: 3
t1: tensor([[7],
        [6],
        [8],
        [5],
        [1],
        [3]]), shape: torch.Size([6, 1]), row: 6, column: 1
t1: tensor([[8, 6, 5],
        [3, 5, 5]]), shape: torch.Size([2, 3]), rows: 2, columns: 3
t2: tensor([[[8, 6, 5],
         [3, 5, 5]]]), shape: torch.Size([1, 2, 3])
t2: tensor([[[8, 6, 5]],

        [[3, 5, 5]]]), shape: torch.Size([2, 1, 3])
t1: tensor([[[[[9]],

          [[1]],

          [[1]]]],



        [[[[5]],

          [[3]],

          [[5]]]]]), shape: torch.Size([2, 1, 3, 1, 1])
t2: tensor([[9, 1, 1],
        [5, 3, 5]]), shape: torch.Size([2, 3])
t1: tensor([[[4, 5, 5, 9],
         [2, 6, 9, 5],
         [3, 1, 2, 2]],

        [[4, 4, 8, 8],
         [9, 8, 3, 6],
         [2, 4, 3, 4]]]), shape: torch.Size([2, 3, 4])
t2: tensor([[[4, 5, 5, 9],
         [4, 4, 8, 8]],

        [[2, 6, 9, 5],
         [9, 8, 3, 6]],

        [[3, 1, 2, 2],
         [2, 4

### 张量的拼接
1. cat()   将多个张量指定的维度拼接起来，不改变维度数，**除了拼接的那个维度外，其他维度必须保持一致**  2维 + 2维 -> 2维
2. stack() 在一个新的维度上连接一系列张量，会增加一个新的维度，并且所有**输入张量的形状必须完全相同**  2维 + 2维 -> 3维

In [71]:
import torch

t1 = torch.randint(1, 10, size=(2, 3))
print(f"t1: {t1}")
t2 = torch.randint(1, 10, size=(2, 3))
print(f"t2: {t2}")

t3 = torch.cat([t1, t2], dim=0)
print(f"t3: {t3}, shape: {t3.shape}")
t3 = torch.cat([t1, t2], dim=1)
print(f"t3: {t3}, shape: {t3.shape}")
print("-" * 50)

t3 = torch.stack([t1, t2], dim=0)
print(f"t3: {t3}, shape: {t3.shape}")
t3 = torch.stack([t1, t2], dim=1)
print(f"t3: {t3}, shape: {t3.shape}")
t3 = torch.stack([t1, t2], dim=2)
print(f"t3: {t3}, shape: {t3.shape}")

t1: tensor([[4, 9, 1],
        [9, 8, 9]])
t2: tensor([[6, 5, 8],
        [5, 9, 2]])
t3: tensor([[4, 9, 1],
        [9, 8, 9],
        [6, 5, 8],
        [5, 9, 2]]), shape: torch.Size([4, 3])
t3: tensor([[4, 9, 1, 6, 5, 8],
        [9, 8, 9, 5, 9, 2]]), shape: torch.Size([2, 6])
--------------------------------------------------
t3: tensor([[[4, 9, 1],
         [9, 8, 9]],

        [[6, 5, 8],
         [5, 9, 2]]]), shape: torch.Size([2, 2, 3])
t3: tensor([[[4, 9, 1],
         [6, 5, 8]],

        [[9, 8, 9],
         [5, 9, 2]]]), shape: torch.Size([2, 2, 3])
t3: tensor([[[4, 6],
         [9, 5],
         [1, 8]],

        [[9, 5],
         [8, 9],
         [9, 2]]]), shape: torch.Size([2, 3, 2])
