### 张量元素类型转换
1. data.type(torch.DoubleTensor)
2. data.half/double/float/short/int/long()

In [5]:
import torch

t1 = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float)
print(f"t1 = {t1}, (元素)类型：{t1.dtype}，（张量）类型：{type(t1)}")

# 直接类型转换
t2 = t1.type(torch.int16)
print(f"t2 = {t2}, (元素)类型：{t2.dtype}，（张量）类型：{type(t2)}")

# 使用half()/double()/float()/short()/int()/long()转换
print(t2.half())
print(t2.double())
print(t2.float())
print(t2.short())
print(t2.int())
print(t2.long())

t1 = tensor([1., 2., 3., 4., 5.]), (元素)类型：torch.float32，（张量）类型：<class 'torch.Tensor'>
t2 = tensor([1, 2, 3, 4, 5], dtype=torch.int16), (元素)类型：torch.int16，（张量）类型：<class 'torch.Tensor'>
tensor([1., 2., 3., 4., 5.], dtype=torch.float16)
tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
tensor([1., 2., 3., 4., 5.])
tensor([1, 2, 3, 4, 5], dtype=torch.int16)
tensor([1, 2, 3, 4, 5], dtype=torch.int32)
tensor([1, 2, 3, 4, 5])


### 张量类型转换
1. 张量转换为 Numpy 数组：使用 Tensor.numpy 函数可以将张量转换为 ndarray 数组，但是共享内存，可以使用 copy 函数避免共享。
2. Numpy 数组转换为张量：使用 from_numpy 可以将ndarray 数组转换为 Tensor，默认共享内存，使用 copy 函数避免共享；使用 torch.tensor 可以将 ndarray 数组转换为 Tensor，默认不共享内存。
3. 标量张量和数字转换：对于只有一个元素的张量，使用 item() 函数将该值从张量中提取出来。

In [6]:
import torch
import numpy as np

# 1. 张量转numpy
t1 = torch.tensor([1,2,3,4])
n1 = t1.numpy()  # 共享
n2 = t1.numpy().copy() # 不共享

t1[0] = 100
print(f"t1: {t1}, type: {type(t1)}")
print(f"n1: {n1}, type: {type(n1)}")
print(f"n1: {n2}, type: {type(n2)}")


# 2. numpy转张量
t2 = torch.from_numpy(n2) # 共享
t3 = torch.tensor(n2) # 不共享
n2[0] = 300
print(f"n1: {t2}, type: {type(t2)}")
print(f"n1: {t3}, type: {type(t3)}")


# 3. 标量转数字
t4 = torch.tensor([1])
a = t4.item()
print(f"n1: {t4}, type: {type(t4)}")
print(f"n1: {a}, type: {type(a)}")

t1: tensor([100,   2,   3,   4]), type: <class 'torch.Tensor'>
n1: [100   2   3   4], type: <class 'numpy.ndarray'>
n1: [1 2 3 4], type: <class 'numpy.ndarray'>
n1: tensor([300,   2,   3,   4]), type: <class 'torch.Tensor'>
n1: tensor([1, 2, 3, 4]), type: <class 'torch.Tensor'>
n1: tensor([1]), type: <class 'torch.Tensor'>
n1: 1, type: <class 'int'>
