### 张量元素类型转换
1. data.type(torch.DoubleTensor)
2. data.half/double/float/short/int/long()

In [5]:
import torch

t1 = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float)
print(f"t1 = {t1}, (元素)类型：{t1.dtype}，（张量）类型：{type(t1)}")

# 直接类型转换
t2 = t1.type(torch.int16)
print(f"t2 = {t2}, (元素)类型：{t2.dtype}，（张量）类型：{type(t2)}")

# 使用half()/double()/float()/short()/int()/long()转换
print(t2.half())
print(t2.double())
print(t2.float())
print(t2.short())
print(t2.int())
print(t2.long())

t1 = tensor([1., 2., 3., 4., 5.]), (元素)类型：torch.float32，（张量）类型：<class 'torch.Tensor'>
t2 = tensor([1, 2, 3, 4, 5], dtype=torch.int16), (元素)类型：torch.int16，（张量）类型：<class 'torch.Tensor'>
tensor([1., 2., 3., 4., 5.], dtype=torch.float16)
tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
tensor([1., 2., 3., 4., 5.])
tensor([1, 2, 3, 4, 5], dtype=torch.int16)
tensor([1, 2, 3, 4, 5], dtype=torch.int32)
tensor([1, 2, 3, 4, 5])
