## 参数初始化
在构建网络后，网络中的参数是需要初始化的，需要初始化的参数主要有**权重和偏置，偏置一般初始化为0即可**，对于权重的初始化会更重要
初始化参数的作用；
1. 防止梯度消失或爆炸，初始权重值过大或过小会导致梯度在反向传播中指数级增大或缩小
2. 提高收敛速度，合理的初始化使得网络的激活值分布适中，有助于梯度高效更新
3. 保持对称性破除，权重的初始化需要打破对称性，否则网络的学习能力会受到限制

### 常见参数初始化方法
1. 随机初始化
均匀分布初始化 -- nn.init.uniform_()：权重参数初始化从区间均匀随机取值，默认区间(0, 1)，可以设置为在 （-$ 1 \over \sqrt{d} $, $ 1 \over \sqrt{d} $) 均匀分布中生成当前神经元的权重，其中d为神经元输入数量。
正态分布初始化 -- nn.init.normal_()：随机初始化从均值为0，标准差为1的高斯分布中取样，使用一些很小的值对参数W进行初始化。
优点：能有效打破对称性
缺点：随机选择范围不当可能导致梯度问题
适用场景：浅层网络或低复杂度模型。隐藏层1-3层，总层数不超过5层。
2. 全0初始化 -- nn.init.zeros_()：将神经网络中的所有权重参数初始化为0
3. 全1初始化 -- nn.init.ones_()：将神经网络中的所有权重参数初始化为1
4. 固定值初始化 -- nn.init.constant_()：将神经网络中的所有权重参数初始化为某个固定值
5. **kaiming初始化，也叫做 HE 初始化 -- nn.init.kaiming_uniform_()/kaiming_normal_()**：HE初始化分为正态分布的HE初始化和均匀分布的HE初始化。正态分布的HE初始化：从[0, std]中抽取样本，std=sqrt(2 / fan_in)。均匀分布的HE初始化：从[-limit, limit]中的均匀分布中抽取样本，limit是sqrt(6 / fan_in)。fan_in是上一层输入的神经元个数  ——————  kaimming + ReLU
6. **xavier初始化，也叫做Glorot初始化 -- nn.init.xavier_uniform_()/xavier_normal_()**：该方法有两种，一种是正态分布的xavier初始化，从[0, std]中抽取样本，std=sqrt(2 / (fan_in + fan_out))。另一种是均匀分布的xavier初始化，它是[-limit, limit]中的均匀分布中抽取样本，limit是sqrt(6 / (fan_in + fan_out))。fan_in是上一层输入的神经元个数，fan_out是传递给下一层的神经元个数，即本层的神经元个数。———— xavier + Sigmoid/Tanh 解决梯度消失问题，都ReLU效果不好

In [9]:
import torch.nn as nn

# 激活函数ReLU及其系列：优先用kaiming
# 激活函数非ReLU：优先用xavier
# 如果是浅层网络：可以考虑使用随机初始化

linear = nn.Linear(5, 3)
nn.init.uniform_(linear.weight)
nn.init.uniform_(linear.bias)
print("随机均匀初始化")
print(linear.weight.data)
print(linear.bias.data)
print("-" * 40)

linear = nn.Linear(5, 3)
nn.init.normal_(linear.weight)
nn.init.normal_(linear.bias)
print("随机正态分布初始化")
print(linear.weight.data)
print(linear.bias.data)
print("-" * 40)

linear = nn.Linear(5, 3)
nn.init.constant_(linear.weight, val=0.3)
nn.init.constant_(linear.bias, val=0.2)
print("固定值初始化")
print(linear.weight.data)
print(linear.bias.data)
print("-" * 40)

linear = nn.Linear(5, 3)
nn.init.zeros_(linear.weight)
nn.init.zeros_(linear.bias)
print("全0初始化")
print(linear.weight.data)
print(linear.bias.data)
print("-" * 40)

linear = nn.Linear(5, 3)
nn.init.ones_(linear.weight)
nn.init.ones_(linear.bias)
print("全1初始化")
print(linear.weight.data)
print(linear.bias.data)
print("-" * 40)

linear = nn.Linear(5, 3)
nn.init.kaiming_normal_(linear.weight)
# nn.init.kaiming_normal_(linear.bias) 无法初始化，因为他是1维的
print("kaiming初始化")
print(linear.weight.data)
# print(linear.bias.data)
print("-" * 40)

linear = nn.Linear(5, 3)
nn.init.normal_(linear.weight)
# nn.init.normal_(linear.bias) 与kaiming同理
print("xavier初始化")
print(linear.weight.data)
# print(linear.bias.data)
print("-" * 40)

随机均匀初始化
tensor([[0.5460, 0.4139, 0.6802, 0.1100, 0.4480],
        [0.4311, 0.9027, 0.9205, 0.7665, 0.5042],
        [0.2543, 0.1033, 0.5995, 0.3106, 0.8172]])
tensor([0.4465, 0.8940, 0.5351])
----------------------------------------
随机正态分布初始化
tensor([[ 0.0699, -0.3635, -0.4666, -1.4551, -0.4541],
        [ 0.5653, -0.2899,  1.3121, -0.7704, -0.3054],
        [ 0.2681,  0.1822, -0.9568, -0.0625, -0.2942]])
tensor([ 0.9076,  0.7555, -0.5845])
----------------------------------------
固定值初始化
tensor([[0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000]])
tensor([0.2000, 0.2000, 0.2000])
----------------------------------------
全0初始化
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([0., 0., 0.])
----------------------------------------
全1初始化
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([1., 1., 1.])
-----

### 搭建神经网络
在Pytorch中定义神经网络其实就是层堆叠的过程，继承自nn.Module，实现两个方法：
1. __init__方法中定义网络中的层结构，主要是全连接层，并进行初始化
2. forward方法，在实例化模型的时候，底层会自动调用该函数。该函数中为初始化定义layer传入数据，及逆行前向传播等。

In [5]:
"""
编码设计：
1. 第一个隐藏层：权重初始化采用标准化的xavier初始化，激活函数使用sigmoid
2. 第二个隐藏层：权重初始化采用标准化的HE初始化，激活函数采用ReLU
3. out输出层线性层  假若多分类，采用softmax做数据归一化
"""
import torch
import torch.nn as nn
from torchsummary import summary

# todo: 1. 搭建神经网络
class ModelDemo(nn.Module):
    def __init__(self):
        # 1. 继承父类
        super().__init__()

        # 2. 定义隐藏层
        self.linear_1 = nn.Linear(3, 3)
        self.linear_2 = nn.Linear(3, 2)
        # 3. 定义输出层
        self.output = nn.Linear(2, 2)

        # 4. 对隐藏层进行初始化
        nn.init.xavier_normal_(self.linear_1.weight)
        nn.init.zeros_(self.linear_1.bias)
        nn.init.kaiming_normal_(self.linear_2.weight)
        nn.init.zeros_(self.linear_2.bias)

    # 向前传播
    def forward(self, x):
        # 输入层 -> 隐藏层1
        x = torch.sigmoid(self.linear_1(x))
        # 隐藏层1 -> 隐藏层2
        x = torch.relu(self.linear_2(x))
        # 隐藏层2 -> 输出层 dim=-1 == 按照行计算
        x = torch.softmax(self.output(x), dim=-1)
        return x


# todo: 2. 模型训练 + 预测
def train():
    # 定义模型
    model = ModelDemo()
    print(f"model: {model}")

    # 获取输入数据
    x = torch.randn(size=(5, 3))
    print(f"x: {x}")
    print(f"x.shape: {x.shape}")
    print(f"x.requires_grad: {x.requires_grad}")

    # 将输入参数加入神经网络计算
    output = model(x)
    print(f"output: {output}")
    print(f"output.shape: {output.shape}")
    print(f"output.requires_grad: {output.requires_grad}")
    print("*" * 40)

    print("================= 计算参数 ================")
    # 参数1：神经网络模型  参数2：数据形状
    summary(model, input_size=(5, 3))

    print("================= 查看模型参数 ================")
    for name, param in model.named_parameters():
        print(f"参数名称：{name}")
        print(f"参数数据：{param}\n")

if __name__ == '__main__':
    train()

model: ModelDemo(
  (linear_1): Linear(in_features=3, out_features=3, bias=True)
  (linear_2): Linear(in_features=3, out_features=2, bias=True)
  (output): Linear(in_features=2, out_features=2, bias=True)
)
x: tensor([[-1.5144,  0.9984, -1.0102],
        [-0.3804, -0.4694, -1.0676],
        [-0.7123,  0.0928, -0.4636],
        [ 0.0965,  0.1866, -0.0805],
        [ 0.9267,  1.1584,  0.2240]])
x.shape: torch.Size([5, 3])
x.requires_grad: False
output: tensor([[0.3767, 0.6233],
        [0.3675, 0.6325],
        [0.3692, 0.6308],
        [0.3636, 0.6364],
        [0.3624, 0.6376]], grad_fn=<SoftmaxBackward0>)
output.shape: torch.Size([5, 2])
output.requires_grad: True
****************************************
================= 计算参数 ================
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 5, 3]              12
            Linear-2                 [-1, 5, 2]     

### 损失函数
损失函数：在深度学习中，**损失函数是用来衡量模型参数的质量的函数**，衡量的方式是比较网络输出和真实输出的差异

#### 多分类任务损失函数 (nn.CrossEntropyLoss)
因为多分类交叉熵损失的公式中包含softmax，所以在输出层，多分类问题中，在使用多分类交叉熵的情况下，输出层可以不用softmax激活函数
在多分类任务通常使用softmax将logits转换为概率的形式，所以多分类的交叉熵损失也叫做**softmax损失**，它的计算方法是
$$ L=-\sum_{i=1}^n{y_i log(S(f_\theta(x_i)))} $$
其中：
1. y是样本x属于某一个类别的真是概率
2. f(x)是样本属于某一类别的预测分数
3. S是softmax激活函数，将属于某一类别的预测分数转换成概率
4. L用来衡量真实值y和预测值f(x)之间差异性的损失结果



In [8]:
import torch
import torch.nn as nn

y_true = torch.tensor([[0, 1, 0], [0, 0, 1]], dtype=torch.float)  # one-hot编码
# y_true = torch.tensor([1, 2])

y_pred = torch.tensor([[0.1, 0.9, 0.2], [0.2, 0.3, 0.7]], dtype=torch.float)

criterion = nn.CrossEntropyLoss()

loss = criterion(y_pred, y_true)
print(f"loss: {loss}")

loss: 0.7442625761032104


#### 二分类任务损失函数 (nn.BCELoss)
在处理二分类任务时，我们不再使用softmax激活函数，而是使用sigmoid激活函数，那损失函数也相应的调整为：
$$ L = -y log(\hat{y}) - (1-y)log(1-\hat{y}) $$
其中：
1. y是样本x属于某一个类别的真实概率
2. $ \hat{y} $是样本属于某一类别的预测概率
3. L是衡量真实值y和预测值$\hat{y}$之间差异性的损失结果

In [11]:
import torch
import torch.nn as nn

y_pred = torch.tensor([0.6901, 0.5423, 0.2639], dtype=torch.float, requires_grad=True)
y_true = torch.tensor([0, 1, 0], dtype=torch.float)
y_pred = torch.sigmoid(y_pred)
criterion = nn.BCELoss()

loss = criterion(y_pred, y_true)
print(f"loss: {loss}")

loss: 0.7962253093719482


#### 回归任务损失函数——MAE损失函数 (nn.L1Loss)
Mean Absolute Error(MAE)也被称为L1 Loss，是以绝对误差作为距离。公式：
$$ L = \frac{1}{n}\sum_{i=1}^n{|y_i-f_\theta(x_i)|} $$
特点：
1. 由于L1 Loss具有稀疏性，为了惩罚较大的值，因为常常将其作为正则项添加到其他loss中作为约束
2. L1 Loss的最大问题是梯度在零点不平滑，导致会跳过极小值

In [12]:
import torch
import torch.nn as nn

y_true = torch.tensor([2.0, 2.0, 2.0])
y_pred = torch.tensor([1.0, 1.0, 1.9])

criterion = nn.L1Loss()
loss = criterion(y_pred, y_true)
print(f"loss: {loss}")

loss: 0.699999988079071


#### MSE损失函数 (nn.MSELoss)
Mean Squared Error(MSE)也被称为L2 Loss或欧氏距离，是以误差的平方和的均值作为距离。公式：
$$ L = \frac{1}{n}\sum_{i=1}^n{(y_i-f_\theta(x_i))^2} $$
特点：
1. L2 Loss也常常作为正则项
2. 当预测值与目标值相差很大时，梯度容易爆炸

In [13]:
import torch
import torch.nn as nn

y_true = torch.tensor([2.0, 2.0, 2.0])
y_pred = torch.tensor([1.0, 1.0, 1.9])

criterion = nn.MSELoss()
loss = criterion(y_pred, y_true)
print(f"loss: {loss}")

loss: 0.6700000166893005


#### Smooth L1损失函数 (nn.SmoothL1Loss)
Smooth L1损失函数是光滑之后的L1。公式：

$$
smooth_{L_1}(x) = \begin{cases} 0.5x^2 && |x| < 1 \\ |x|-0.5 && otherwise \end{cases}
$$
其中：$ x = f(x) - y $ 为真实值和预测值的差值
该函数是一个分段函数
1. 在[-1, 1]之间实际上就是L2损失，这样解决了L1的不光滑问题
2. 在[-1, 1]区间外，实际上就是L1损失，这样就解决了梯度爆炸的问题

In [14]:
import torch
import torch.nn as nn

y_true = torch.tensor([2.0, 2.0, 2.0])
y_pred = torch.tensor([1.0, 1.0, 1.9])

criterion = nn.SmoothL1Loss()
loss = criterion(y_pred, y_true)
print(f"loss: {loss}")

loss: 0.33500000834465027


### 网络优化方法
1. Epoch: 使用全部数据对模型进行一次完整的训练，训练轮次
2. Batch_size: 使用训练集中的小部分样本对模型权重进行反向传播的参数更新，每次训练每批次样本数量
3. Iteration: 使用一个 Batch 数据都模型进行一次参数更新的过程

在深度学习中，梯度下降的几种方式根本区别就在于Batch Size不同，如下表：

| 梯度下降方式 | Training Set Size | Batch Size | Number of Batches |
|:--- |:------------------|:--- |:------------------|
| BGD | N                 | N | 1                 |
| SGD | N                 | 1 | N                 |
| Mini-Batch | N                 | B | N/B + 1           |

注：上表中 Mini-Batch 的Batch个数为 N/B + 1是针对未整除的情况。整除则是N/B 直接用 (N + B - 1)/B 替代
